export {
  DEFAULT_CHANNEL_DOC_STALE_AFTER_DAYS,
  DEFAULT_CHANNEL_DOC_STALE_AFTER_MS,
  DEFAULT_CHANNEL_ACTIVITY_SIGNAL_TTL_DAYS,
  DEFAULT_CHANNEL_HEALTH_THRESHOLD,
  DEFAULT_CHANNEL_PROBE_COOLDOWN_DAYS,
  DEFAULT_CHANNEL_PROBE_MIN_SUCCESS,
  classifyTelegramChannelError,
  computeLiveCanSendMsgs,
  deriveTelegramChannelLiveFacts,
  evaluateChannelPromotionHealth,
  evaluateChannelSendability,
  getChannelDocStaleness,
  mergeHydratedChannelFacts,
  normalizeChannelId,
  resolvePromotionFailureAction,
  shouldHydrateBeforeFinalReject,
  type ChannelDocumentSnapshot,
  type ChannelHydrationStatus,
  type ChannelPromotionHealthInput,
  type ChannelPromotionHealthOptions,
  type ChannelPromotionHealthResult,
  type ChannelSendabilityResult,
  type ChannelStalePolicy,
  type ChannelStalenessResult,
  type ChannelStateScope,
  type DefaultBannedRightsSnapshot,
  type HydratedChannelMergeResult,
  type PromotionFailureAction,
  type PromotionFailureActionInput,
  type TelegramChannelErrorClassification,
  type TelegramChannelLiveFacts,
} from './channel-state';
